feature: forgot password
capstone-kelompok-7/backend-disappear pull request #19
Opened 2023-11-11 01:58 UTC by masnann

feature: forgot password
![image](https://github.com/capstone-kelompok-7/backend-disappear/assets/120388738/76acf79f-da2c-4843-a4e6-deff2f30a0d5)

2023-11-12 16:43 UTC, RianIhsan requested changes
Ada review sikit mas anan

2023-11-12 16:43 UTC, RianIhsan commented on module/feature/auth/service/service.go
> +	}
Mas anan ini pake fmt? gk pake return err aja mas anan?

2023-11-12 18:51 UTC, garindradeksa approved these changes

2023-11-13 13:23 UTC, masnann commented on module/feature/auth/service/service.go
> +	}
done

2023-11-13 14:41 UTC, RianIhsan approved these changes

2023-11-13 14:42 UTC, merged