update feature/voucher
capstone-kelompok-7/backend-disappear pull request #6
Opened 2023-11-07 10:01 UTC by anzalass

2023-11-07 10:21 UTC, masnann commented
- kodenya masih belum sesuai
   responsenya udah dibikin, tinggal manggil aja di utils, biar returnya sama
- masukin bukti screenshot di PR
- reviewer minimal 2, bukan termasuk admin(adminnya anan)
- assignees di isi nama yang bikin pull request
- labelsnya diisi, kalo fitur baru baru feature, klo improvment atau update berarti labelnya improvment

2023-11-07 10:25 UTC, RianIhsan requested changes

2023-11-07 10:25 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +		})
Mas, ini return nya harus pake format yang udah dibikin di folder utils > response , biar konsisten

2023-11-07 10:25 UTC, RianIhsan commented on module/voucher/handler/handler.go
>  		return c.JSON(http.StatusCreated, map[string]interface{}{
Yang ini juga ganti response nya menggunakan utils > response.go

2023-11-07 10:25 UTC, RianIhsan commented on module/voucher/handler/handler.go
>  		return c.JSON(http.StatusCreated, map[string]interface{}{
Ini juga, pokoknya jangan ada return C.JSON, return nya harus pake yang dari folder utils > response.go

2023-11-07 10:28 UTC, anzalass commented
okeii

Pada Sel, 7 Nov 2023 17.25, Rian Ihsan Ardiansyah ***@***.***>
menulis:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In module/voucher/handler/handler.go
> <https://github.com/capstone-kelompok-7/backend-disappear/pull/6#discussion_r1384693111>
> :
>
> > +		return c.JSON(http.StatusCreated, map[string]interface{}{
> +			"message": "Berhasil.",
> +			"data":    domain.VoucherResponseFormatter(*result),
> +		})
>
> Mas, ini return nya harus pake format yang udah dibikin di folder utils >
> response , biar konsisten
> ------------------------------
>
> In module/voucher/handler/handler.go
> <https://github.com/capstone-kelompok-7/backend-disappear/pull/6#discussion_r1384697335>
> :
>
> > @@ -76,7 +77,7 @@ func (h *VoucherHandler) GetAllVouchers() echo.HandlerFunc {
>  		result, err := h.service.GetAllVouchers(pagee, limitt, search)
>  		if err != nil {
>  			c.Logger().Error("handler: failed create voucher:", err.Error())
> -			return response.SendErrorResponse(c, http.StatusInternalServerError, "Internal Server Error")
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", err.Error()))
>  		}
>
>  		return c.JSON(http.StatusCreated, map[string]interface{}{
>
> Yang ini juga ganti response nya menggunakan utils > response.go
> ------------------------------
>
> In module/voucher/handler/handler.go
> <https://github.com/capstone-kelompok-7/backend-disappear/pull/6#discussion_r1384699778>
> :
>
> > @@ -128,8 +129,8 @@ func (h *VoucherHandler) DeleteVoucherById() echo.HandlerFunc {
>
>  		result := h.service.DeleteVoucherById(voucheridfix)
>  		if result != nil {
> -			c.Logger().Error("handler: failed get voucher:", result.Error())
> -			return response.SendErrorResponse(c, http.StatusInternalServerError, "Internal Server Error")
> +			c.Logger().Error("handler: failed delete voucher:", result.Error())
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", result.Error()))
>  		}
>
>  		return c.JSON(http.StatusCreated, map[string]interface{}{
>
> Ini juga, pokoknya jangan ada return C.JSON, return nya harus pake yang
> dari folder utils > response.go
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/capstone-kelompok-7/backend-disappear/pull/6#pullrequestreview-1717331804>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2APJUC3YL5OBGBMRJJNPTDYDIEC5AVCNFSM6AAAAAA7A4XFBWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMJXGMZTCOBQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-11-07 14:27 UTC, RianIhsan requested changes
Semangat mas anzalan improve dikit lagi dibagian handler nya, ada beberapa review terkait error handling sama success handling

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			"data": domain.VoucherResponseFormatter(*result),
Kalo gak salah pada bagian ini bisa seperti ini

```
return response.SendSuccessResponse(c."Berhasil Get Voucher by ID", domain.VoucherResponseFormatter(result))
```
jadi gk perlu pake mapstring lagi

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			"Berhasil")
mas coba di liat pagination yang di product, boleh tuh di contek biar sedikit rapih code nya + clean code

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", err.Error()))
Ini juga mas, gk perlu pake fmt, ini kan konsep nya udh rest API, jadi ngikut format si `response.SendErrorResponse` aja, contoh 

```
return response.SendErrorResponse(c, http.StatusInternalServerError, "Internal Server Error")

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			"data": domain.VoucherResponseFormatter(*result),
Kalo gak salah pada bagian ini bisa seperti ini

```
return response.SendSuccessResponse(c."Berhasil Get Voucher by ID", domain.VoucherResponseFormatter(result))
```
jadi gk perlu pake mapstring lagi

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", err.Error()))
Ini juga mas, gk perlu pake fmt, ini kan konsep nya udh rest API, jadi ngikut format si `response.SendErrorResponse` aja, contoh 

```
return response.SendErrorResponse(c, http.StatusInternalServerError, "Internal Server Error")

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", err.Error()))
Ini juga mas, gk perlu pake fmt, ini kan konsep nya udh rest API, jadi ngikut format si `response.SendErrorResponse` aja, contoh 

```
return response.SendErrorResponse(c, http.StatusInternalServerError, "Internal Server Error")

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", result.Error()))
ini juga sama

2023-11-07 14:27 UTC, RianIhsan commented on module/voucher/handler/handler.go
> +			return response.SendErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Internal Server Error, %s", err.Error()))
ini juga

2023-11-07 14:29 UTC, masnann requested changes
coba di cek lagi ya kalo masalah response, terima kasih mas anzalaasss

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  		if input.Name == "" || input.Category == "" || input.Code == "" || input.Description == "" || input.Discouunt < 0 || input.EndDate == "" || input.StartDate == "" {
di bikin request sendiri di domain, terus di binding, terus di validasi (utils validasi.go)
contoh bisa di cek di auth handler register

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  }
bisa di cek dibagian login user juga, ada contoh buat nampilin datanya
jadi nanti bikin isi respon sendiri

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  		if input.Name == "" || input.Category == "" || input.Code == "" || input.Description == "" || input.Discouunt < 0 || input.EndDate == "" || input.StartDate == "" {
sesuaikan juga binding yang ini

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  	}
ini juga di perbaiki

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  		}
ini juga responnya masih belm sesuai, cari aja di auth buat respon internal server error

2023-11-07 14:29 UTC, masnann commented on module/voucher/handler/handler.go
>  	}
ini juga di cek lagi ya

2023-11-08 04:45 UTC, anzalass commented on module/voucher/handler/handler.go
>  		return c.JSON(http.StatusCreated, map[string]interface{}{
done

2023-11-08 04:45 UTC, anzalass commented on module/voucher/handler/handler.go
> +			"data": domain.VoucherResponseFormatter(*result),
done

2023-11-08 04:45 UTC, anzalass commented on module/voucher/handler/handler.go
> +			"Berhasil")
done

2023-11-08 04:48 UTC, masnann approved these changes
mantap, overall sudah sesuai

2023-11-08 07:32 UTC, RianIhsan approved these changes

2023-11-08 08:51 UTC, bsyrlhabibi approved these changes

2023-11-08 08:55 UTC, nurulalyh approved these changes

2023-11-08 08:58 UTC, merged